### ISSUE TITLE
MPL license

### ISSUE THREAD

**Issue by andig** [enbility/spine-go#22]
Noticed during https://github.com/evcc-io/evcc/pull/13998 that this package now relies on github.com/hashicorp/golang-lru/v2 which is under MPL license. In general, projects like spf13/viper are trying to move away from depending on hashicorp due to their licensing changes. I'm no expert but wondering if MPL is compatible with MIT?

**Comment by DerAndereAndi** [comment]
Replaced it with another package anyway: https://github.com/enbility/spine-go/commit/c96bc14d05b081e395e7f13f7d54147629d585d5
