### ISSUE TITLE
UpdateData filterData There is an issue where the update does not correspond

### ISSUE THREAD

**Issue by lyn0904** [enbility/spine-go#47]
![image](https://github.com/user-attachments/assets/fa9970de-02eb-486c-a913-40a6e68d4e60)

**Comment by lyn0904** [comment]
@ @DerAndereAndi

**Comment by lyn0904** [comment]
After testing, only the first bit of the array can be updated. @DerAndereAndi

**Comment by DerAndereAndi** [comment]
This data model should never be updated from a remote and doesn't allow writing from a remote device.
